-- noinspection SqlDialectInspectionForFile

INSERT INTO TEAM (TEAM_NAME, TEAM_NUMBER, TEAM_DESCRIPTION) VALUES ('Alphas', '20201024', 'FE Team for creating apps');
INSERT INTO TEAM (TEAM_NAME, TEAM_NUMBER, TEAM_DESCRIPTION) VALUES ('Delta', '20201025', 'BE Team for creating apis');
INSERT INTO TEAM (TEAM_NAME, TEAM_NUMBER, TEAM_DESCRIPTION) VALUES ('Omega', '20201026', 'Testing Team for load and security tests');

INSERT INTO MEMBERS (MEMBER_NAME, NICK_NAME, LOCATION, COUNTRY) VALUES ('Dexter Morgan', 'Dexter', 'Miami', 'USA');
INSERT INTO MEMBERS (MEMBER_NAME, NICK_NAME, LOCATION, COUNTRY) VALUES ('Ethan Hunt', 'Hunt', 'Florida', 'USA');
INSERT INTO MEMBERS (MEMBER_NAME, NICK_NAME, LOCATION, COUNTRY) VALUES ('Doctor Who', 'Doctor', 'Unknown', 'Gallifrey');
INSERT INTO MEMBERS (MEMBER_NAME, NICK_NAME, LOCATION, COUNTRY) VALUES ('Bhattachary', 'Bhattu', 'Andhra pradesh', 'India');
INSERT INTO MEMBERS (MEMBER_NAME, NICK_NAME, LOCATION, COUNTRY) VALUES ('Kill Bill Pandey', 'Kill Bill', 'Andhra pradesh', 'India');

INSERT INTO TEAM_ALLOCATIONS (TEAM_ID, MEMBER_ID, ALLOCATION_START_DATE) VALUES ((SELECT TEAM_ID FROM TEAM WHERE TEAM_NUMBER = '20201024'), (SELECT MEMBER_ID FROM MEMBERS WHERE NICK_NAME = 'Dexter'), '2020-10-24');