CREATE TABLE TEAM(
  TEAM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TEAM_NAME VARCHAR(16) NOT NULL,
  TEAM_NUMBER BIGINT NOT NULL UNIQUE,
  TEAM_DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE MEMBERS(
  MEMBER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MEMBER_NAME VARCHAR(64),
  NICK_NAME VARCHAR(64),
  LOCATION VARCHAR(64),
  COUNTRY VARCHAR(32)
);

CREATE TABLE TEAM_ALLOCATIONS(
  ALLOCATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TEAM_ID BIGINT NOT NULL,
  MEMBER_ID BIGINT NOT NULL,
  ALLOCATION_START_DATE DATE,
  ALLOCATION_END_DATE DATE
);

ALTER TABLE TEAM_ALLOCATIONS ADD FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID);
ALTER TABLE TEAM_ALLOCATIONS ADD FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);
CREATE INDEX IDX_ALLOCATION_START_DATE_ ON TEAM_ALLOCATIONS(ALLOCATION_START_DATE);
